# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Pull request checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Flake checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flake checks
        run: nix flake check
