# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Pull request checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Flake checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Restore nix store from cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: checks-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}
          restore-prefixes-first-match: checks-${{ runner.os }}-
          gc-max-store-size-linux: 0
          purge: true
          purge-prefixes: checks-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - name: Run flake checks
        run: nix flake check
