# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release website

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - assets/**
      - nix/**
      - "!nix/wasm-server-runner/**"
      - "!nix/**.just"
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
      - flake.lock

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build wasm bundle
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Restore nix store from cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: release-${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '**/flake.lock', 'rust-toolchain.toml', 'nix/wasm/*.nix') }}
          restore-prefixes-first-match: release-${{ runner.os }}-
          gc-max-store-size-linux: 0
          purge: true
          purge-prefixes: release-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - name: Build wasm bundle
        run: nix develop .#ci --command just nix wasm build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: result/html

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 15

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
